# Generated by Django 4.2.2 on 2023-06-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gada', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
