# Generated by Django 4.2.2 on 2023-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gada', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='xyz.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
