# Generated by Django 4.2.2 on 2023-06-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gada', '0005_alter_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('digital', models.BooleanField(default=False)),
            ],
        ),
    ]
