# Generated by Django 4.2.2 on 2023-06-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gada', '0008_order_shippingadderess_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
