# Generated by Django 4.2.2 on 2023-06-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gada', '0009_order_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ManyToManyField(related_name='product', to='Gada.product'),
        ),
    ]
