# Generated by Django 4.2.2 on 2023-07-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gada', '0016_cart_is_active_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
