# Generated by Django 4.2.2 on 2023-07-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gada', '0018_product_qunatity_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
